#!/usr/bin/env python3
"""Turn a .gcode file into a C header the firmware can run from flash.

    ./tools/gcode_to_header.py demo.gcode > module/gcode_job.h

Comments and blank lines are dropped so nothing is wasted in flash. Until
there is a UART or SD feeder, this is how a job gets onto the board.
"""
import sys, os

if len(sys.argv) != 2:
    sys.exit("usage: gcode_to_header.py <file.gcode>")

src = sys.argv[1]
lines = []
with open(src) as f:
    for raw in f:
        line = raw.split(";")[0].strip()
        if not line:
            continue
        lines.append(line.replace("\\", "\\\\").replace('"', '\\"'))

name = os.path.basename(src)
print("/* Generated by tools/gcode_to_header.py from %s — do not edit. */" % name)
print("#ifndef GCODE_JOB_H")
print("#define GCODE_JOB_H")
print()
print("static const char *const gcode_job[] = {")
for line in lines:
    print('  "%s",' % line)
print("};")
print()
print("#define GCODE_JOB_LINES  (sizeof(gcode_job) / sizeof(gcode_job[0]))")
print()
print("#endif /* GCODE_JOB_H */")
