#include "comms.h"
#include "gcode.h"
#include "motion_control.h"
#include "stepper.h"
#include "main.h"
#include <string.h>
#include <stdio.h>

/* Transport. Once USB_DEVICE/CDC is generated by CubeMX this picks it up
 * on its own; until then the writes go nowhere and the rest still builds. */
#if defined(__has_include)
#  if __has_include("usbd_cdc_if.h")
#    include "usbd_cdc_if.h"
#    define COMMS_HAVE_USB 1
#  endif
#endif

#define LINE_MAX          128

static char     line[LINE_MAX];
static uint16_t line_len = 0;
static uint8_t  line_overflow = 0;

/* Bytes from the interrupt to the main loop */
static volatile uint8_t  rx[COMMS_RX_BUFFER];
static volatile uint16_t rx_head = 0, rx_tail = 0;

/* Set by '?' and '!' in the interrupt, acted on in the main loop */
static volatile uint8_t want_status = 0;
static volatile uint8_t alarm = 0;

void comms_print(const char *s)
{
#ifdef COMMS_HAVE_USB
  uint16_t len = (uint16_t)strlen(s);
  /* CDC_Transmit_FS refuses while the previous packet is still going out;
   * a job sends little, so a short spin is enough. */
  for (uint32_t tries = 0; tries < 50000U; tries++)
  {
    if (CDC_Transmit_FS((uint8_t *)s, len) == USBD_OK)
      return;
  }
#else
  (void)s;
#endif
}

static void report_status(void)
{
  char buf[96];
  int32_t x100 = (int32_t)(mc_x() * 100.0f);
  int32_t y100 = (int32_t)(mc_y() * 100.0f);
  snprintf(buf, sizeof(buf), "<%s|MPos:%ld.%02ld,%ld.%02ld|Qfree:%u>\n",
           alarm ? "Alarm" : (stepper_busy() ? "Run" : "Idle"),
           (long)(x100 / 100), (long)(x100 < 0 ? -x100 % 100 : x100 % 100),
           (long)(y100 / 100), (long)(y100 < 0 ? -y100 % 100 : y100 % 100),
           (unsigned)stepper_queue_free());
  comms_print(buf);
}

void comms_init(void)
{
  line_len = 0;
  line_overflow = 0;
  rx_head = rx_tail = 0;
  want_status = 0;
  alarm = 0;
  comms_print("CoreXY v0.1 ready\n");
}

void comms_rx(const uint8_t *data, uint32_t len)
{
  for (uint32_t i = 0; i < len; i++)
  {
    uint8_t ch = data[i];

    /* handled immediately, never queued */
    if (ch == '?')
    {
      want_status = 1;
      continue;
    }
    if (ch == '!' || ch == 0x18)
    {
      stepper_abort();
      alarm = 1;
      rx_head = rx_tail;          /* throw away what was in flight */
      continue;
    }
    if (ch == '~')
    {
      alarm = 0;
      continue;
    }

    uint16_t next = (uint16_t)((rx_head + 1U) % COMMS_RX_BUFFER);
    if (next == rx_tail)
      break;                      /* full: the host sent too much */
    rx[rx_head] = ch;
    rx_head = next;
  }
}

static int16_t rx_get(void)
{
  if (rx_tail == rx_head)
    return -1;
  uint8_t ch = rx[rx_tail];
  rx_tail = (uint16_t)((rx_tail + 1U) % COMMS_RX_BUFFER);
  return (int16_t)ch;
}

void comms_task(void)
{
  if (want_status)
  {
    want_status = 0;
    report_status();
  }

  int16_t ch;
  while ((ch = rx_get()) >= 0)
  {
    if (ch == '\n' || ch == '\r')
    {
      if (line_len == 0 && !line_overflow)
        continue;                 /* empty line, say nothing */

      line[line_len] = '\0';
      if (line_overflow)
      {
        comms_print("error:line too long\n");
      }
      else if (alarm)
      {
        comms_print("error:alarm, send ~ first\n");
      }
      else
      {
        gcode_status_t st = gcode_line(line);
        if (st == GCODE_OK || st == GCODE_EMPTY)
        {
          comms_print("ok\n");
        }
        else
        {
          char buf[32];
          snprintf(buf, sizeof(buf), "error:%d\n", (int)st);
          comms_print(buf);
        }
      }

      line_len = 0;
      line_overflow = 0;

      /* One line at a time: gcode_line() may block while the queue is
       * full, and the status request above should get through. */
      return;
    }

    if (line_len < LINE_MAX - 1)
      line[line_len++] = (char)ch;
    else
      line_overflow = 1;
  }
}
